# Generated by Django 5.1.2 on 2024-10-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=50)),
                ('statusColor', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False, verbose_name='Task ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('dueDate', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='todo_app.status')),
            ],
        ),
    ]
